# Generated by Django 5.1.7 on 2025-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_task_completed_task_due_date_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2024-03-09'),
            preserve_default=False,
        ),
    ]
